### ISSUE TITLE
Docker Swarm Stack Deploy at Jenkins Cluster Compose file 

### ISSUE THREAD

**Issue by WoodProgrammer** [hypriot/blog#83]
I modified your docker-compose file shown as below 
```
version: "3"

networks:
  jenkins_swarm:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: 10.10.2.0/16

services:
  jenkins:
    image: csanchez/jenkins-swarm
    expose:
      - 8080
      - 50000
    ports:
      - 8080:8080
    restart: always
    networks:
      - jenkins_swarm
    environment:
      - "constraint:NODE==cl-leader"

  worker:
    image: csanchez/jenkins-swarm-slave
    command: -username jenkins -password jenkins -executors 1
    networks:
      - jenkins_swarm
    environment:
      - "JENKINS_PORT_8080_TCP_ADDR=jenkins"
      - "JENKINS_PORT_8080_TCP_PORT=8080"

```

I created 2 docker-machine and create small swarm cluster , I run this script 
**$ docker stack deploy --compose-file docker-compose.yml jenkinsdemo** 

after look at the logs of slave node service I have a error as shown as below 
 

```
SEVERE: RetryException occurred
hudson.plugins.swarm.RetryException: Failed to fetch slave info from Jenkins, HTTP response code: 401
	at hudson.plugins.swarm.SwarmClient.discoverFromMasterUrl(SwarmClient.java:233)
	at hudson.plugins.swarm.Client.run(Client.java:146)
	at hudson.plugins.swarm.Client.main(Client.java:119)

Jun 02, 2018 11:26:43 PM hudson.plugins.swarm.Client run
INFO: Retrying in 10 seconds
```

What is the problem accually ? 

Notice : I could not see the slave node , UI at master node . 

Thank you for your helping .

**Comment by StefanScherer** [comment]
Jenkins is more secure now since the blog post.

I tried to start the stack.
Open the Jenkins server UI and you have to unlock it first.
Fetch the initial password from the jenkins container.

Example:
```
$ docker ps
CONTAINER ID        IMAGE                                 COMMAND                  CREATED             STATUS              PORTS                 NAMES
3688522051c5        csanchez/jenkins-swarm-slave:latest   "/usr/local/bin/jenk…"   3 minutes ago       Up 2 minutes                              jenkins_worker.1.ozj4cep3x0kdw9f5zth29qid9
99682890ae2a        csanchez/jenkins-swarm:latest         "/bin/tini -- /usr/l…"   5 minutes ago       Up 4 minutes        8080/tcp, 50000/tcp   jenkins_jenkins.1.zr3kf4dsshvtfpo9mxtwoo32r
~/code/hypriot/jenkins
$ docker exec 9968 cat /var/jenkins_home/secrets/initialAdminPassword
6d7e090009e54fe5a6cfe5f6bcf4f072
```

Log in, install the plugins and then create the First Admin User -> jenkins / jenkins

After some seconds the worker should be able to join.

And another good idea is to have at least one volume to persist the Jenkins data folder.

```yaml
version: "3"

networks:
  jenkins_swarm:

volumes:
    jenkins_data: {}

services:
  jenkins:
    image: csanchez/jenkins-swarm
    ports:
      - 8080:8080
    restart: always
    networks:
      - jenkins_swarm
    volumes:
      - jenkins_data:/var/jenkins_home
    environment:
      - "constraint:NODE==cl-leader"

  worker:
    image: csanchez/jenkins-swarm-slave
    command: -username jenkins -password jenkins -executors 1
    networks:
      - jenkins_swarm
    environment:
      - "JENKINS_PORT_8080_TCP_ADDR=jenkins"
      - "JENKINS_PORT_8080_TCP_PORT=8080"
```

**Comment by WoodProgrammer** [comment]
Thank you so much for your helping. @StefanScherer 
I've tried on my local docker swarm environment and it worked!

**Comment by StefanScherer** [comment]
Congrats!
