### ISSUE TITLE
error when running docker container on macos

### ISSUE THREAD

**Issue by ORESoftware** [hypriot/blog#95]
I was reading this article which is really fantastic
https://blog.hypriot.com/post/run-your-own-github-like-service-with-docker/

I ran this:

```bash
docker run -ti --name my-go-git-server -p 8022:22 -p 3000:3000 --volume `pwd`/gogs-data/:/data hypriot/rpi-gogs-raspbian
```

but I get this error:

```

[ ok ] Starting OpenBSD Secure Shell server: sshd.
sending incremental file list

sent 2,800 bytes  received 41 bytes  5,682.00 bytes/sec
total size is 370,720  speedup is 130.49
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      0          120510      46/qemu-arm     
tcp6       0      0 :::22                   :::*                    LISTEN      0          120513      46/qemu-arm     
  PID TTY          TIME CMD
   46 ?        00:00:00 sshd
  136 ?        00:00:00 ps
fatal error: rt_sigaction failure

runtime stack:
runtime.throw(0xb4c345)
        /goroot/src/runtime/panic.go:491 +0xa4
runtime.setsig(0x40, 0xcb660, 0xc21b01)
        /goroot/src/runtime/os_linux.c:302 +0xa8
runtime.initsig()
        /goroot/src/runtime/signal_unix.c:39 +0x88
mstart()
        /goroot/src/runtime/proc.c:856 +0x6c
runtime.mstart()
        /goroot/src/runtime/proc.c:836 +0x4c

goroutine 1 [runnable]:
runtime.main()
        /goroot/src/runtime/proc.go:16
runtime.goexit()
        /goroot/src/runtime/asm_arm.s:1322 +0x4
```

it should work on macos right?

For what it's worth, here is the gogs data in the shared volume:

<kbd>
<img width="360" alt="Screen Shot 2019-05-02 at 5 45 04 PM" src="https://user-images.githubusercontent.com/11139560/57115172-1c14d400-6d02-11e9-9117-155e897fdb34.png">
</kbd>

**Comment by ORESoftware** [comment]
perhaps this belongs in a GOGS repo instead?
